version: "3.9"

services:
  client:
    container_name: sd_frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/frontend'
      - 'node_modules:/frontend/node_modules'
    ports:
      - '4173:4173'
    environment:
      - NODE_ENV=development
volumes:
  node_modules: {}
