apiVersion: v1
kind: Service
metadata:
  name: sd-frontend-service
spec:
  #type: NodePort
  type: LoadBalancer
  selector:
    app: sd-frontend
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
      nodePort: 30230
