name: Test and push images

on:
  push:
    branches:
      - "main"
    paths:
      - "client/**"
      - "server/**"

jobs:
  docker_client:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./client/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sd_client:${{ github.run_number }}

  docker_server:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sd_server:${{ github.run_number }}

  test_ubuntu_client:
    name: Test Client on Ubuntu latest Node.js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use latest Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '*'
      - name: npm install, build, and test
        run: |
          cd client
          npm install
          npm run build --if-present
          npm test

  test_windows_client:
    name: Test Client on Windows latest Node.js
    runs-on: windows-latest
    needs: test_ubuntu_client
    steps:
      - uses: actions/checkout@v1
      - name: Use latest Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '*'
      - name: npm install, build, and test
        run: |
          cd client
          npm install
          npm test

  test_ubuntu_server:
    name: Test Server on Ubuntu latest Node.js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use latest Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '*'
      - name: npm install, build, and test
        run: |
          cd server
          npm install
          npm run build --if-present
          npm test

  test_windows_server:
    name: Test Server on Windows latest Node.js
    runs-on: windows-latest
    needs: test_ubuntu_server
    steps:
      - uses: actions/checkout@v1
      - name: Use latest Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '*'
      - name: npm install, build, and test
        run: |
          cd server
          npm install
          npm test
